//Pipeline that uses docker as agent to checkout build and test using jenkins
pipeline {
    agent {
        docker {
            image 'node:14' 
            args '-u root:root'
        }
    }
    environment {
        // Set environment variables for React Native and Java
        JAVA_HOME = '/usr/local/openjdk-8'
        ANDROID_HOME = '/opt/android-sdk'
        PATH = "${env.PATH}:${env.JAVA_HOME}/bin:${env.ANDROID_HOME}/tools:${env.ANDROID_HOME}/platform-tools"
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Daoud-Hussain/Fitness-Fuse-Mobile.git'
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'npx react-native run-android'
            }
        }
        stage('Test') {
            steps {
                echo 'No tests specified'
            }
        }
    }
    post {
       success {
            echo 'Build and Test stages completed successfully.'
        }

        failure {
            echo 'Build or Test stage failed.'
        }
    }
}
